# Generated by Django 2.1.5 on 2019-04-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, upload_to='products/%Y_%m_%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/%Y_%m_%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/%Y_%m_%d')),
                ('image4', models.ImageField(blank=True, upload_to='products/%Y_%m_%d')),
            ],
        ),
    ]
