# Generated by Django 2.1.5 on 2019-04-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190415_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Owner',
        ),
    ]
