# Generated by Django 2.1.5 on 2019-04-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190415_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='Owner',
        ),
    ]
