# Generated by Django 2.1.5 on 2019-04-21 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_auto_20190415_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Happian',
            field=models.ManyToManyField(blank=True, related_name='Happian', to=settings.AUTH_USER_MODEL),
        ),
    ]
