# Generated by Django 2.1.5 on 2019-04-21 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_auto_20190421_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Happian',
        ),
        migrations.AddField(
            model_name='product',
            name='Happy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='happyproduct', to=settings.AUTH_USER_MODEL),
        ),
    ]
