# Generated by Django 2.1.5 on 2019-04-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190421_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Happy',
        ),
    ]
