# Generated by Django 2.1.5 on 2019-04-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190421_1609'),
        ('accounts', '0003_remove_user_receive_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Happyproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product'),
        ),
    ]
