# Generated by Django 2.1.7 on 2019-03-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190317_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='receive_newsletter',
        ),
    ]
