# Generated by Django 2.1.5 on 2019-04-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_happyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Happyproduct',
        ),
    ]
